export enum BusinessStatusMessage {
	SUCCESS = 'SUCCESS',
	INVALID_PARAMETER = 'INVALID_PARAMETER',
	MISSING_PARAMETER = 'MISSING_PARAMETER',
	DATA_NOT_FOUND = 'DATA_NOT_FOUND',
	UNAUTHORIZED = 'UNAUTHORIZED',
	UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
	UNACCEPTABLE_REDUNDANCY = 'UNACCEPTABLE_REDUNDANCY',
}
